const state = { user: null, csrf: "", page: "dashboard", devices: [], prompts: [], models: [], requests: [], selectedDeviceId: null, socket: null, reconnectTimer: null, deviceDrafts: {}, requestLoadVersion: 0 };
const $ = (selector) => document.querySelector(selector);
const contentRoot = () => $("#page-content");
function esc(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (c) { return {"&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;"}[c]; }); }
function date(value) { return value ? new Date(value).toLocaleString("zh-CN", {hour12:false}) : "-"; }
function statusLabel(status) { var labels={online:"在线",offline:"离线",waiting_capture:"等待截屏",capturing:"截屏中",uploading:"上传中",processing:"模型处理中",completed:"已完成",failed:"失败",cancelled:"已取消",pending:"待审批",active:"正常",disabled:"已禁用",deleted:"已删除",approved:"已通过",rejected:"已拒绝",expired:"已过期"}; var tone=["completed","online","active","approved"].includes(status)?"success":["failed","cancelled","disabled","rejected"].includes(status)?"danger":["processing","waiting_capture","capturing","uploading","pending"].includes(status)?"warning":"neutral"; return '<span class="status-label '+tone+'"><span class="status-dot '+(tone === "success" ? "online" : tone === "warning" ? "warning" : tone === "danger" ? "danger" : "")+'"></span>'+esc(labels[status] || status)+'</span>'; }
function notify(message, bad) { var node=document.createElement("div"); node.className="toast"+(bad?" error":""); node.textContent=message; var region=$("#toast-region");while(region.children.length>=3)region.firstElementChild.remove();region.appendChild(node); setTimeout(function(){node.remove();},4200); }
function setMessage(selector, message, bad) { var node=$(selector); if(node){node.textContent=message;node.className="form-message"+(bad?" error":" success");} }
function values(form) { return Object.fromEntries(new FormData(form).entries()); }
async function api(path, options) { options=options||{}; var method=(options.method||"GET").toUpperCase(); var headers=new Headers(options.headers||{}); if(options.body && !(options.body instanceof FormData)) headers.set("Content-Type","application/json"); if(method !== "GET" && state.csrf) headers.set("X-CSRF-Token",state.csrf); var response=await fetch(path,Object.assign({},options,{method:method,headers:headers,credentials:"same-origin"})); var data={}; try{data=await response.json();}catch(_){ } if(response.status===401&&state.user)clearSession(); if(!response.ok) throw new Error((data.error&&data.error.message)||("请求失败（"+response.status+"）")); return data; }
function modal(inner) { $("#modal-root").innerHTML='<div class="modal-backdrop" data-close-modal><div class="modal" onclick="event.stopPropagation()">'+inner+'</div></div>'; }
function closeModal() { $("#modal-root").innerHTML=""; }
function showApp() { $("#auth-view").classList.add("hidden");$("#app-view").classList.remove("hidden");$("#account-name").textContent=state.user.display_name;$("#account-role").textContent=state.user.role === "admin" ? "管理员" : "普通用户";document.querySelectorAll(".admin-only").forEach(function(n){n.classList.toggle("hidden",state.user.role !== "admin");});connectBrowser();navigate("dashboard"); }
async function boot() {
  document.addEventListener("input",function(e){if(e.target.closest("#request-form"))saveDeviceDraft();});
  document.addEventListener("change",function(e){if(e.target.closest("#request-form"))saveDeviceDraft();});
  $("#login-form").addEventListener("submit",async function(e){e.preventDefault();try{var r=await api("/api/auth/login",{method:"POST",body:JSON.stringify(values(e.currentTarget))});state.user=r.user;state.csrf=r.csrf_token;showApp();}catch(err){setMessage("#login-message",err.message,true);}});
  $("#register-form").addEventListener("submit",async function(e){e.preventDefault();var form=e.currentTarget;try{await api("/api/auth/register",{method:"POST",body:JSON.stringify(values(form))});form.reset();setMessage("#register-message","注册申请已提交，请等待管理员审批");}catch(err){setMessage("#register-message",err.message,true);}});
  document.querySelectorAll("[data-auth-tab]").forEach(function(button){button.addEventListener("click",function(){document.querySelectorAll("[data-auth-tab]").forEach(function(n){n.classList.toggle("active",n===button);});$("#login-form").classList.toggle("hidden",button.dataset.authTab!=="login");$("#register-form").classList.toggle("hidden",button.dataset.authTab!=="register");});});
  document.querySelectorAll("[data-page]").forEach(function(button){button.addEventListener("click",function(){navigate(button.dataset.page);});});
  $("#logout-button").addEventListener("click",async function(){if(state.socket){state.socket.onclose=null;state.socket.close();state.socket=null;}try{await api("/api/auth/logout",{method:"POST"});clearSession();}catch(err){notify(err.message,true);connectBrowser();}});
  $("#profile-button").addEventListener("click",profileModal);
  $("#modal-root").addEventListener("click",function(e){if(e.target.dataset.closeModal !== undefined)closeModal();});
  var session=await fetch("/api/auth/me",{credentials:"same-origin"}).then(function(r){return r.json();});
  if(session.authenticated){state.user=session.user;state.csrf=session.csrf_token;showApp();}
}
function clearSession(){state.user=null;state.csrf="";clearTimeout(state.reconnectTimer);if(state.socket){state.socket.onclose=null;state.socket.close();state.socket=null;}closeModal();contentRoot().innerHTML="";state.devices=[];state.requests=[];state.models=[];state.prompts=[];state.deviceDrafts={};state.selectedDeviceId=null;$("#auth-view").classList.remove("hidden");$("#app-view").classList.add("hidden");}
function connectBrowser(){
  clearTimeout(state.reconnectTimer);
  if(!state.user)return;
  if(state.socket){state.socket.onclose=null;state.socket.close();}
  var scheme=location.protocol==="https:"?"wss:":"ws:";
  var socket=new WebSocket(scheme+"//"+location.host+"/ws/browser");state.socket=socket;
  socket.onopen=function(){if(state.socket!==socket)return;$("#connection-indicator").innerHTML='<span class="status-dot online"></span><span>实时连接正常</span>';refreshDevices().catch(function(e){notify(e.message,true);});};
  socket.onclose=async function(){if(state.socket!==socket||!state.user)return;$("#connection-indicator").innerHTML='<span class="status-dot warning"></span><span>实时连接断开</span>';try{var current=await api("/api/auth/me");if(!current.authenticated){clearSession();return;}state.user=current.user;state.csrf=current.csrf_token;}catch(_){}if(state.user)state.reconnectTimer=setTimeout(connectBrowser,4000);};
  socket.onerror=function(){if(state.socket===socket)$("#connection-indicator").innerHTML='<span class="status-dot danger"></span><span>实时连接异常</span>';};
  socket.onmessage=function(e){if(state.socket!==socket)return;try{realtime(JSON.parse(e.data));}catch(err){notify("实时消息处理失败："+err.message,true);}};
}
function saveDeviceDraft(){var form=$("#request-form");if(form&&state.selectedDeviceId)state.deviceDrafts[state.selectedDeviceId]=values(form);}
function restoreDeviceDraft(){
  var form=$("#request-form"),draft=state.deviceDrafts[state.selectedDeviceId];
  if(!form||!draft)return;
  ["prompt_id","model_profile_id","model_name","reasoning_effort","question"].forEach(function(name){var input=form.elements.namedItem(name);if(input&&draft[name]!==undefined){input.value=draft[name];if(name==="model_profile_id")input.dispatchEvent(new Event("change"));}});
  form.elements.namedItem("force").checked=draft.force==="on";
}
async function refreshDevices(){
  await loadDevices();
  if(state.page!=="dashboard"||!$("#device-list"))return;
  await loadRequests(state.selectedDeviceId);
  if(state.page!=="dashboard"||!$("#device-list"))return;
  renderDeviceList();renderDeviceDetail();
}
function realtime(message){if(message.type === "request_update"&&message.request){var row=message.request;var i=state.requests.findIndex(function(x){return x.id===row.id;});if(i>=0)state.requests[i]=Object.assign({},state.requests[i],row);else state.requests.unshift(row);if(state.page === "dashboard"&&$("#latest-request")&&row.device_id===state.selectedDeviceId){$("#latest-request").innerHTML=requestResult(row);if(["completed","failed","cancelled"].includes(row.status)&&$("#cancel-active"))$("#cancel-active").remove();}if(state.page === "history"&&["completed","failed","cancelled"].includes(row.status))renderHistory();}if(message.type === "device_update"){refreshDevices().catch(function(e){notify(e.message,true);});}if(message.type === "pairing_update"){notify(message.status === "approved" ? "客户端已许可连接" : message.status === "expired" ? "连接许可已失效" : "客户端拒绝了连接",message.status !== "approved");refreshDevices().catch(function(e){notify(e.message,true);});}}
async function navigate(page){state.page=page;document.querySelectorAll("[data-page]").forEach(function(b){b.classList.toggle("active",b.dataset.page===page);});var title={dashboard:["控制中心","设备控制"],history:["问答历史","问答历史"],prompts:["提示词库","提示词"],models:["模型配置","模型配置"],credentials:["客户端访问","客户端凭证"],users:["账号管理","账号管理"],audit:["审计日志","审计日志"]}[page]||["控制中心","设备控制"];$("#page-eyebrow").textContent=title[0];$("#page-title").textContent=title[1];try{await renderCurrent();}catch(err){notify(err.message,true);}}
async function renderCurrent(){if(state.page==="dashboard")return renderDashboard();if(state.page==="history")return renderHistory();if(state.page==="prompts")return renderPrompts();if(state.page==="models")return renderModels();if(state.page==="credentials")return renderCredentials();if(state.page==="users")return renderUsers();if(state.page==="audit")return renderAudit();}
async function loadDevices(){state.devices=(await api("/api/devices")).items;if(!state.selectedDeviceId&&state.devices.length)state.selectedDeviceId=state.devices[0].id;if(state.selectedDeviceId&&!state.devices.find(function(d){return d.id===state.selectedDeviceId;}))state.selectedDeviceId=state.devices[0]&&state.devices[0].id;}
async function loadPrompts(){state.prompts=(await api("/api/prompts")).items;}
async function loadModels(includeDisabled){state.models=(await api("/api/models")).items.filter(function(m){return includeDisabled===true||m.enabled;});}
async function loadRequests(device){var version=++state.requestLoadVersion;var suffix=device ? "?device_id="+encodeURIComponent(device) : "";var result=await api("/api/requests"+suffix);if(version===state.requestLoadVersion)state.requests=result.items;}
function requestResult(row){return '<div class="answer-panel"><div class="panel-title"><div><h4>问答结果</h4><p>'+date(row.created_at)+' · '+esc(row.model_name)+' · 推理 '+esc(({none:"默认",low:"低",medium:"中",high:"高",xhigh:"极高"})[row.reasoning_effort]||"中")+'</p></div>'+statusLabel(row.status)+'</div>'+(row.error?'<div class="request-status failed">'+esc(row.error)+'</div>':'')+(row.reasoning?'<details class="reasoning-box"><summary>推理过程</summary><div class="prose">'+esc(row.reasoning)+'</div></details>':'')+'<div class="prose answer-prose">'+esc(row.answer||(row.status==="processing"?"模型正在输出...":"等待结果..."))+'</div>'+(row.screenshot_available?'<div class="toolbar" style="margin-top:14px"><a class="secondary-button" href="'+row.screenshot_url+'" target="_blank" rel="noreferrer">查看截图</a></div>':'')+'</div>';}
async function renderDashboard(){contentRoot().innerHTML='<div class="page-intro"><div><span class="eyebrow">连接设备</span><h3>设备控制</h3></div><form id="pair-form" class="inline-form"><label>连接码<input class="code-input" name="connection_code" inputmode="numeric" maxlength="9" pattern="[0-9]{9}" placeholder="000000000" required></label><button class="primary-button" type="submit">请求连接</button></form></div><div class="dashboard-grid"><section class="panel"><div class="panel-title"><div><h3>已授权设备</h3></div><button class="secondary-button" id="refresh-devices">刷新</button></div><div id="device-list"><p class="muted">正在加载设备...</p></div></section><section id="device-detail" class="panel"><div class="detail-empty">正在加载设备数据...</div></section></div>';
  $("#pair-form").addEventListener("submit",pairDevice);$("#refresh-devices").addEventListener("click",function(){loadDevices().then(renderDashboard);});try{await Promise.all([loadDevices(),loadPrompts(),loadModels()]);await loadRequests(state.selectedDeviceId);if(state.page!=="dashboard"||!$("#device-list"))return;renderDeviceList();renderDeviceDetail();}catch(err){if(!$("#device-list"))return;$("#device-list").innerHTML='<p class="muted">'+esc(err.message)+'</p>';}}
function renderDeviceList(){var list=$("#device-list");if(!state.devices.length){list.innerHTML='<p class="muted">暂无设备</p>';return;}list.innerHTML=state.devices.map(function(d){return '<div class="device-row '+(d.id===state.selectedDeviceId?"selected":"")+'" data-device-id="'+d.id+'"><div class="device-main"><div class="device-name">'+esc(d.name)+'</div><div class="device-meta">'+esc(d.platform||"Windows")+' · 连接码尾号 '+esc(d.connection_code_last4||"已失效")+'</div></div><div class="device-state">'+statusLabel(d.online?"online":"offline")+'</div></div>';}).join("");list.querySelectorAll("[data-device-id]").forEach(function(n){n.addEventListener("click",async function(){state.selectedDeviceId=Number(n.dataset.deviceId);await loadRequests(state.selectedDeviceId);renderDeviceList();renderDeviceDetail();});});}
function renderDeviceDetail(){var root=$("#device-detail"),device=state.devices.find(function(d){return d.id===state.selectedDeviceId;});if(!device){root.innerHTML='<div class="detail-empty">选择一个已授权设备开始操作。</div>';return;}var active=state.requests.find(function(r){return r.device_id===device.id&&["waiting_capture","capturing","uploading","processing"].includes(r.status);});root.innerHTML='<div class="panel-title"><div><h3>'+esc(device.name)+'</h3><div>'+statusLabel(device.online?"online":"offline")+'</div></div><div class="toolbar"><button class="secondary-button" id="disconnect-device">断开设备</button><button class="danger-button" id="unpair-device">解绑并使连接码失效</button></div></div>'+(device.code_invalidated?'<div class="request-status failed">连接码已失效</div>':'')+'<form id="request-form" class="control-grid"><div class="form-grid"><label>提示词<select name="prompt_id" required>'+state.prompts.map(function(p){return '<option value="'+p.id+'" '+(p.id===device.default_prompt_id?"selected":"")+'>'+esc(p.name)+(p.is_global?" · 全局":"")+'</option>';}).join("")+'</select></label><label>模型配置<select name="model_profile_id" id="model-profile-select" required>'+state.models.map(function(m){return '<option value="'+m.id+'" '+(m.id===device.default_model_profile_id?"selected":"")+'>'+esc(m.name)+' · '+esc(m.provider)+'</option>';}).join("")+'</select></label><label>模型名称<select name="model_name" id="model-name-select" required></select></label><label>推理强度<select name="reasoning_effort"><option value="none" '+(device.reasoning_effort==="none"?"selected":"")+'>默认（不指定强度）</option><option value="low" '+(device.reasoning_effort==="low"?"selected":"")+'>低</option><option value="medium" '+(device.reasoning_effort==="medium"?"selected":"")+'>中</option><option value="high" '+(device.reasoning_effort==="high"?"selected":"")+'>高</option><option value="xhigh" '+(device.reasoning_effort==="xhigh"?"selected":"")+'>极高</option></select></label><label class="full">补充问题<textarea name="question" rows="3" maxlength="5000" placeholder="例如：请只回答屏幕右侧的第二道题"></textarea></label></div><div class="control-actions"><button class="primary-button" type="submit" '+(device.online&&!device.code_invalidated?"":"disabled")+'>截屏并提问</button><label class="checkbox-line"><input type="checkbox" name="force"> 强制中断设备当前请求</label>'+(active?'<button type="button" class="danger-button" id="cancel-active">中断当前请求</button>':'')+'</div></form><div id="latest-request">'+(state.requests.find(function(r){return r.device_id===device.id;})?requestResult(state.requests.find(function(r){return r.device_id===device.id;})):'<div class="detail-empty">暂无问答记录</div>')+'</div>';
  var ms=$("#model-profile-select"),update=function(){var p=state.models.find(function(m){return m.id===Number(ms.value);});$("#request-form [name=reasoning_effort] option[value=none]").textContent=p&&p.provider==="gemini"?"关闭推理":"默认（不指定强度）";$("#model-name-select").innerHTML=(p&&p.models||[]).map(function(n){return '<option value="'+esc(n)+'" '+(p.id===device.default_model_profile_id&&n===device.default_model_name?"selected":"")+'>'+esc(n)+'</option>';}).join("");};if(ms){ms.addEventListener("change",update);update();}restoreDeviceDraft();$("#request-form").addEventListener("submit",submitRequest);$("#disconnect-device").addEventListener("click",function(){deviceAction("disconnect");});$("#unpair-device").addEventListener("click",function(){deviceAction("unpair");});if($("#cancel-active"))$("#cancel-active").addEventListener("click",function(){api("/api/requests/"+active.id+"/cancel",{method:"POST"}).then(function(){notify("请求已中断");loadRequests(device.id).then(renderDeviceDetail);}).catch(function(e){notify(e.message,true);});});}
async function pairDevice(e){e.preventDefault();try{var r=await api("/api/devices/pair",{method:"POST",body:JSON.stringify({connection_code:new FormData(e.currentTarget).get("connection_code")})});if(r.status==="approved"){notify("设备已授权");await loadDevices();renderDashboard();return;}notify("已发送授权请求，请在客户端确认");var id=r.pair_request_id,timer=setInterval(async function(){try{var x=await api("/api/pairings/"+id);if(x.status!=="pending"){clearInterval(timer);notify(x.status==="approved"?"客户端已授权":"授权结果："+x.status,x.status!=="approved");await refreshDevices();}}catch(_){clearInterval(timer);}},1000);}catch(err){notify(err.message,true);}}
async function submitRequest(e){e.preventDefault();var deviceId=state.selectedDeviceId,v=values(e.currentTarget);try{var r=await api("/api/devices/"+deviceId+"/requests",{method:"POST",body:JSON.stringify({prompt_id:Number(v.prompt_id),model_profile_id:Number(v.model_profile_id),model_name:v.model_name,reasoning_effort:v.reasoning_effort,question:v.question,force:e.currentTarget.force.checked})});var live=state.requests.find(function(row){return row.id===r.request.id;});state.requests=state.requests.filter(function(row){return row.id!==r.request.id;});state.requests.unshift(live||r.request);delete state.deviceDrafts[deviceId];notify("已发送截屏请求");if(state.page==="dashboard"&&state.selectedDeviceId===deviceId)renderDeviceDetail();}catch(err){notify(err.message,true);}}
async function deviceAction(action){var d=state.devices.find(function(x){return x.id===state.selectedDeviceId;});if(!d||!confirm(action==="unpair"?"确定解绑设备？":"确定断开设备？"))return;try{await api("/api/devices/"+d.id+"/"+action,{method:"POST"});notify(action==="unpair"?"设备已解绑，连接码已失效":"已发送断开指令");await loadDevices();renderDashboard();}catch(err){notify(err.message,true);}}

async function renderHistory(){contentRoot().innerHTML='<div class="page-intro"><div><span class="eyebrow">历史记录</span><h3>问答历史</h3></div><button id="refresh-history" class="secondary-button">刷新记录</button></div><section class="panel"><div id="history-list"><p class="muted">正在加载...</p></div></section>';$("#refresh-history").addEventListener("click",renderHistory);try{await loadRequests();var list=$("#history-list");if(!list)return;list.innerHTML=state.requests.length?state.requests.map(function(r){return '<article class="history-item" data-request-id="'+r.id+'"><div class="history-head"><strong>'+esc(r.device_name)+'</strong>'+statusLabel(r.status)+'</div><div class="history-question">'+esc(r.question||"未填写补充问题")+'</div><div class="muted">'+date(r.created_at)+' · '+esc(r.model_name)+'</div></article>';}).join(""): '<p class="muted">暂无记录</p>';list.querySelectorAll("[data-request-id]").forEach(function(n){n.addEventListener("click",function(){var r=state.requests.find(function(x){return x.id===n.dataset.requestId;});if(r){modal('<h3>问答详情</h3>'+requestResult(r)+'<div class="modal-actions"><button class="secondary-button" onclick="closeModal()">关闭</button></div>');}});});}catch(err){notify(err.message,true);}}

async function renderPrompts(){contentRoot().innerHTML='<div class="page-intro"><div><span class="eyebrow">提示词库</span><h3>提示词模板</h3></div><button class="primary-button" id="new-prompt">新建提示词</button></div><section class="panel"><div id="prompt-table" class="data-table-wrap"><p class="muted">正在加载...</p></div></section>';$("#new-prompt").addEventListener("click",function(){promptModal();});await loadPrompts();var t=$("#prompt-table");if(!t)return;t.innerHTML='<table><thead><tr><th>名称</th><th>范围</th><th>说明</th><th>更新时间</th><th>操作</th></tr></thead><tbody>'+state.prompts.map(function(p){return '<tr><td><strong>'+esc(p.name)+'</strong></td><td>'+ (p.is_global?"全局":"个人")+'</td><td>'+esc(p.description)+'</td><td>'+date(p.updated_at)+'</td><td><button class="secondary-button" data-edit="'+p.id+'">编辑</button> <button class="danger-button" data-delete="'+p.id+'">删除</button></td></tr>';}).join("")+'</tbody></table>';t.querySelectorAll("[data-edit]").forEach(function(b){b.addEventListener("click",function(){promptModal(state.prompts.find(function(p){return p.id===Number(b.dataset.edit);}));});});t.querySelectorAll("[data-delete]").forEach(function(b){b.addEventListener("click",function(){deletePrompt(Number(b.dataset.delete));});});}
function promptModal(p){p=p||null;modal('<h3>'+(p?"编辑提示词":"新建提示词")+'</h3><form id="prompt-form" class="stack-form"><label>名称<input name="name" value="'+esc(p&&p.name||"")+'" required></label><label>说明<input name="description" value="'+esc(p&&p.description||"")+'"></label><label>提示词内容<textarea name="content" rows="10" required>'+esc(p&&p.content||"")+'</textarea></label>'+((state.user.role==="admin"&&!p)?'<label class="checkbox-line"><input type="checkbox" name="is_global" checked> 作为全局模板</label>':'')+'<div class="modal-actions"><button type="button" class="secondary-button" onclick="closeModal()">取消</button><button class="primary-button" type="submit">保存</button></div></form>');$("#prompt-form").addEventListener("submit",async function(e){e.preventDefault();var v=values(e.currentTarget);v.is_global=Boolean(e.currentTarget.is_global&&e.currentTarget.is_global.checked);try{await api(p?"/api/prompts/"+p.id:"/api/prompts",{method:p?"PUT":"POST",body:JSON.stringify(v)});closeModal();notify("提示词已保存");renderPrompts();}catch(err){notify(err.message,true);}});}
async function deletePrompt(id){if(!confirm("确定删除这个提示词？"))return;try{await api("/api/prompts/"+id,{method:"DELETE"});notify("提示词已删除");renderPrompts();}catch(err){notify(err.message,true);}}

async function renderModels(){contentRoot().innerHTML='<div class="page-intro"><div><span class="eyebrow">模型配置</span><h3>模型 API 配置</h3></div><button class="primary-button" id="new-model">新建配置</button></div><section class="panel"><div id="model-table" class="data-table-wrap"><p class="muted">正在加载...</p></div></section>';$("#new-model").addEventListener("click",function(){modelModal();});await loadModels(true);var t=$("#model-table");if(!t)return;t.innerHTML='<table><thead><tr><th>名称</th><th>协议</th><th>端点</th><th>模型</th><th>Key</th><th>范围</th><th>操作</th></tr></thead><tbody>'+state.models.map(function(m){return '<tr><td><strong>'+esc(m.name)+'</strong></td><td>'+esc(m.provider)+'</td><td class="muted">'+esc(m.endpoint)+'</td><td>'+m.models.map(esc).join(", ")+'</td><td>••••'+esc(m.api_key_last4)+'</td><td>'+(m.is_global?"全局":"个人")+'</td><td><button class="secondary-button" data-edit-model="'+m.id+'">编辑</button> <button class="danger-button" data-disable-model="'+m.id+'">'+(m.enabled?"停用":"启用")+'</button></td></tr>';}).join("")+'</tbody></table>';t.querySelectorAll("[data-edit-model]").forEach(function(b){b.addEventListener("click",function(){modelModal(state.models.find(function(m){return m.id===Number(b.dataset.editModel);}));});});t.querySelectorAll("[data-disable-model]").forEach(function(b){b.addEventListener("click",function(){disableModel(Number(b.dataset.disableModel));});});}
function modelModal(m){m=m||null;var options=m&&m.options?JSON.stringify(m.options,null,2):JSON.stringify({},null,2);modal('<h3>'+(m?"编辑模型配置":"新建模型配置")+'</h3><form id="model-form" class="stack-form"><div class="form-grid"><label>配置名称<input name="name" value="'+esc(m&&m.name||"")+'" required></label><label>协议<select name="provider" '+(m?"disabled":"")+'><option value="deepseek" '+(m&&m.provider==="deepseek"?"selected":"")+'>DeepSeek Chat Completions</option><option value="openai_chat" '+(m&&m.provider==="openai_chat"?"selected":"")+'>OpenAI Chat Completions</option><option value="openai_responses" '+(m&&m.provider==="openai_responses"?"selected":"")+'>OpenAI Responses</option><option value="gemini" '+(m&&m.provider==="gemini"?"selected":"")+'>Gemini</option></select></label><label class="full">API 端点<input name="endpoint" value="'+esc(m&&m.endpoint||"")+'" placeholder="https://api.example.com/v1/chat/completions" required></label><label>模型名称（每行一个）<textarea name="models" rows="4" required>'+esc(m&&m.models.join("\n")||"")+'</textarea></label><label>API Key'+(m?"（留空表示不修改）":"")+'<input name="api_key" type="password" autocomplete="new-password" '+(m?"":"required")+'></label><label>超时时间（秒）<input name="timeout_seconds" type="number" min="10" max="600" value="'+(m&&m.timeout_seconds||120)+'"></label><label class="full">可选标准参数 JSON<textarea name="options" rows="5">'+esc(options)+'</textarea></label></div>'+((state.user.role==="admin"&&!m)?'<label class="checkbox-line"><input type="checkbox" name="is_global" checked> 作为全局配置</label>':'')+'<div class="modal-actions"><button type="button" class="secondary-button" onclick="closeModal()">取消</button><button class="primary-button" type="submit">保存配置</button></div></form>');$("#model-form").addEventListener("submit",async function(e){e.preventDefault();var f=e.currentTarget,v=values(f);v.models=v.models.split(/\r?\n|,/).map(function(x){return x.trim();}).filter(Boolean);v.timeout_seconds=Number(v.timeout_seconds);v.is_global=Boolean(f.is_global&&f.is_global.checked);try{await api(m?"/api/models/"+m.id:"/api/models",{method:m?"PUT":"POST",body:JSON.stringify(v)});closeModal();notify("模型配置已保存");renderModels();}catch(err){notify(err.message,true);}});}
async function disableModel(id){var model=state.models.find(function(m){return m.id===id;});if(!model)return;var enabled=!model.enabled;if(!confirm(enabled?"确定启用模型配置？":"确定停用模型配置？"))return;try{await api("/api/models/"+id,{method:"PUT",body:JSON.stringify({enabled:enabled})});notify(enabled?"模型配置已启用":"模型配置已停用");renderModels();}catch(err){notify(err.message,true);}}

async function renderCredentials(){contentRoot().innerHTML='<div class="page-intro"><div><span class="eyebrow">客户端访问</span><h3>客户端凭证</h3></div></div><section class="section-stack"><section class="panel"><div class="panel-title"><div><h3>创建凭证</h3></div></div><form id="credential-form" class="inline-form"><label>凭证名称<input name="name" placeholder="例如：办公室电脑" required></label><button class="primary-button" type="submit">创建凭证</button></form></section><section class="panel"><div id="credential-table" class="data-table-wrap"><p class="muted">正在加载...</p></div></section></section>';$("#credential-form").addEventListener("submit",createCredential);var rows=(await api("/api/credentials")).items;$("#credential-table").innerHTML='<table><thead><tr><th>名称</th><th>凭证尾号</th><th>绑定设备</th><th>创建时间</th><th>最后使用</th><th>状态</th><th>操作</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td><strong>'+esc(r.name)+'</strong></td><td>••••'+esc(r.token_last4)+'</td><td>'+(r.device_id?esc(r.device_id.slice(0,12)):"未绑定")+'</td><td>'+date(r.created_at)+'</td><td>'+date(r.last_used_at)+'</td><td>'+statusLabel(r.revoked?"disabled":"active")+'</td><td>'+(r.revoked?"-":'<button class="danger-button" data-revoke="'+r.id+'">撤销</button>')+'</td></tr>';}).join("")+'</tbody></table>';$("#credential-table").querySelectorAll("[data-revoke]").forEach(function(b){b.addEventListener("click",function(){revokeCredential(Number(b.dataset.revoke));});});}
async function createCredential(e){e.preventDefault();var form=e.currentTarget;try{var r=await api("/api/credentials",{method:"POST",body:JSON.stringify(values(e.currentTarget))});modal('<h3>凭证已创建</h3><div class="token-display">'+esc(r.token)+'</div><div class="modal-actions"><button class="primary-button" onclick="closeModal();renderCredentials()">我已保存</button></div>');form.reset();}catch(err){notify(err.message,true);}}
async function revokeCredential(id){if(!confirm("确定撤销凭证？"))return;try{await api("/api/credentials/"+id,{method:"DELETE"});notify("凭证已撤销");renderCredentials();}catch(err){notify(err.message,true);}}

async function renderUsers(){if(state.user.role!=="admin")return navigate("dashboard");contentRoot().innerHTML='<div class="page-intro"><div><span class="eyebrow">账号管理</span><h3>账号管理</h3></div><button class="secondary-button" id="refresh-users">刷新</button></div><section class="panel"><div id="user-table" class="data-table-wrap"><p class="muted">正在加载...</p></div></section>';$("#refresh-users").addEventListener("click",renderUsers);var rows=(await api("/api/admin/users")).items;$("#user-table").innerHTML='<table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>注册备注</th><th>创建时间</th><th>操作</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td><strong>'+esc(r.display_name)+'</strong><div class="muted">'+esc(r.username)+'</div></td><td>'+(r.role==="admin"?"管理员":"普通用户")+'</td><td>'+statusLabel(r.status)+(r.locked_until?'<div class="muted">锁定至 '+date(r.locked_until)+'</div>':'')+'</td><td>'+esc(r.registration_note)+'</td><td>'+date(r.created_at)+'</td><td><div class="toolbar">'+(r.status==="pending"?'<button class="primary-button" data-user-action="approve" data-user-id="'+r.id+'">批准</button>':'')+(r.status==="active"&&r.id!==state.user.id?'<button class="danger-button" data-user-action="disable" data-user-id="'+r.id+'">禁用</button>':'')+(r.status==="disabled"?'<button class="secondary-button" data-user-action="enable" data-user-id="'+r.id+'">启用</button>':'')+'<button class="secondary-button" data-user-action="unlock" data-user-id="'+r.id+'">解锁</button><button class="secondary-button" data-user-action="reset" data-user-id="'+r.id+'">重置密码</button>'+(r.id!==state.user.id&&r.status!=="deleted"?'<button class="danger-button" data-user-action="delete" data-user-id="'+r.id+'">删除</button>':'')+'</div></td></tr>';}).join("")+'</tbody></table>';$("#user-table").querySelectorAll("[data-user-action]").forEach(function(b){b.addEventListener("click",function(){userAction(Number(b.dataset.userId),b.dataset.userAction);});});}
async function userAction(id,action){if(action==="delete"){if(!confirm("确定删除账号？"))return;try{await api("/api/admin/users/"+id,{method:"DELETE"});notify("账号已删除");renderUsers();}catch(err){notify(err.message,true);}return;}var body={};if(action==="approve"||action==="enable")body.status="active";if(action==="disable")body.status="disabled";if(action==="unlock")body.unlock=true;if(action==="reset"){var p=prompt("请输入新的临时密码");if(!p)return;body.reset_password=p;}try{await api("/api/admin/users/"+id,{method:"PATCH",body:JSON.stringify(body)});notify("账号已更新");renderUsers();}catch(err){notify(err.message,true);}}
async function renderAudit(){if(state.user.role!=="admin")return navigate("dashboard");contentRoot().innerHTML='<div class="page-intro"><div><span class="eyebrow">审计记录</span><h3>审计日志</h3></div><button class="secondary-button" id="refresh-audit">刷新</button></div><section class="panel"><div id="audit-table" class="data-table-wrap"><p class="muted">正在加载...</p></div></section>';$("#refresh-audit").addEventListener("click",renderAudit);var rows=(await api("/api/admin/audit-logs")).items;$("#audit-table").innerHTML='<table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>目标</th><th>来源</th><th>详情</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+date(r.created_at)+'</td><td>'+esc(r.username)+'</td><td>'+esc(r.action)+'</td><td>'+esc(r.target_type)+" / "+esc(r.target_id)+'</td><td>'+esc(r.ip_address)+'</td><td class="muted">'+esc(r.detail)+'</td></tr>';}).join("")+'</tbody></table>';}
function profileModal(){modal('<h3>账号设置</h3><p class="muted">当前账号：'+esc(state.user.username)+' · '+esc(state.user.display_name)+'</p><form id="password-form" class="stack-form"><label>当前密码<input name="current_password" type="password" required></label><label>新密码<input name="new_password" type="password" minlength="8" required></label><div class="modal-actions"><button type="button" class="secondary-button" onclick="closeModal()">取消</button><button class="primary-button" type="submit">修改密码</button></div></form>');$("#password-form").addEventListener("submit",async function(e){e.preventDefault();try{var result=await api("/api/auth/change-password",{method:"POST",body:JSON.stringify(values(e.currentTarget))});state.csrf=result.csrf_token;closeModal();notify("密码已修改");connectBrowser();}catch(err){notify(err.message,true);}});}
boot().catch(function(err){notify(err.message,true);});

